axieinfinity/ronin-dpos-contracts

contracts/mocks/validator/MockRoninValidatorSetExtended.sol, hardhat.config.ts
- Continue work in #89 
- Allow unlimited contract size on hardhat network to pass compilation of mocking of validator set contract.
=> Upgrade solc version. Allow unlimited contract size on hardhat net.

contracts/interfaces/validator/info-fragments/ICommonInfo.sol, contracts/mocks/validator/MockValidatorSet.sol, contracts/ronin/validator/CoinbaseExecution.sol, contracts/ronin/validator/RoninValidatorSet.sol, contracts/ronin/validator/SlashingExecution.sol, contracts/ronin/validator/storage-fragments/CommonStorage.sol, test/helpers/ronin-validator-set.ts, test/validator/RoninValidatorSet.test.ts
- Fix #78 
- Allow admin to withdraw deprecated reward from ValidatorSet contract to StakingVesting contract.
=> [ValidatortSet] Support withdrawing jailed reward

contracts/ronin/staking/DelegatorStaking.sol, test/staking/Staking.test.ts
- https://skymavis.atlassian.net/browse/PSC-106?atlOrigin=eyJpIjoiN2UzY2MzM2I2NjVmNDg2MzkzZGJjNzFlNjFiMTYxOWIiLCJwIjoiaiJ9
=> [Staking] Disallow validators to delegate to other validator

contracts/interfaces/staking/ICandidateStaking.sol, contracts/interfaces/staking/IStaking.sol, contracts/interfaces/validator/info-fragments/ICommonInfo.sol, contracts/ronin/staking/CandidateStaking.sol, contracts/ronin/staking/Staking.sol, contracts/ronin/validator/CoinbaseExecution.sol, contracts/ronin/validator/RoninValidatorSet.sol, contracts/ronin/validator/SlashingExecution.sol, test/helpers/ronin-validator-set.ts, test/validator/RoninValidatorSet.test.ts
- https://skymavis.atlassian.net/browse/PSC-107?atlOrigin=eyJpIjoiM2YxYjNhNTMwYzk1NDYzZjhhNjhiNTY2ZThkMGM4YTQiLCJwIjoiaiJ9
- Recycle slashed staking amount / jailed reward amount / deprecated submitted reward -> staking vesting contract
- The recycle is done at the end of every period
=> [ValidatorSet] Recycle deprecated rewards

contracts/interfaces/staking/ICandidateStaking.sol, contracts/interfaces/validator/ICandidateManager.sol, contracts/ronin/staking/CandidateStaking.sol, contracts/ronin/validator/CandidateManager.sol, test/staking/Staking.test.ts
- https://skymavis.atlassian.net/browse/PSC-108?atlOrigin=eyJpIjoiM2EyZDZmODE2OTZmNGJmNjk4Y2Q5M2IwOGJiY2QxOTIiLCJwIjoiaiJ9
- Allow pool admin to update the commission rate of a validator
- `requestUpdateCommissionRate(address _consensusAddr, uint256 _rate)`
=> [Staking|CandidateManager] Allow pool admin to update commission rate of validator

contracts/interfaces/staking/ICandidateStaking.sol, contracts/interfaces/validator/ICandidateManager.sol, contracts/mocks/validator/MockValidatorSet.sol, contracts/ronin/staking/CandidateStaking.sol, contracts/ronin/validator/CandidateManager.sol, contracts/ronin/validator/CoinbaseExecution.sol, contracts/ronin/validator/RoninValidatorSet.sol, src/config.ts, src/deploy/proxy/ronin-validator-proxy.ts, src/utils.ts, test/helpers/fixture.ts, test/integration/Configuration.test.ts, test/staking/Staking.test.ts
- See https://skymavis.atlassian.net/jira/software/projects/PSC/boards/47?selectedIssue=PSC-108
| Old | New |
| --- | ----------- |
| `requestUpdateCommissionRate(address _consensusAddr, uint256 _rate)` | `requestUpdateCommissionRate(address _consensusAddr, uint256 _effectiveDaysOnwards, uint256 _commissionRate)` |
=> [CandidateManager] Implement effective date for commission rate

contracts/interfaces/staking/IBaseStaking.sol, contracts/interfaces/staking/ICandidateStaking.sol, contracts/libraries/AddressArrayUtils.sol, contracts/ronin/staking/BaseStaking.sol, contracts/ronin/staking/CandidateStaking.sol, contracts/ronin/staking/DelegatorStaking.sol, contracts/ronin/validator/CandidateManager.sol, test/bridge/BridgeTracking.test.ts, test/helpers/address-set-types.ts, test/integration/ActionSlashValidators.test.ts, test/integration/ActionSubmitReward.test.ts, test/integration/ActionWrapUpEpoch.test.ts, test/maintainance/Maintenance.test.ts, test/slash/CreditScore.test.ts, test/slash/SlashIndicator.test.ts, test/staking/Staking.test.ts, test/validator/RoninValidatorSet.test.ts
- Assert `poolAdmin`, `candidateAdmin`, `treasuryAddr` must be of the same
- Assert `poolAdmin`, `consensusAddr`, `bridgeAddr` must be distinct
- Introduce terms of `existPool` and `activePool`
+ An `existPool` is a pool that has been created once in the contract, regardless of the status of the corresponding validator candidate, including existent / kicked / re-joined candidates.
+ An `activePool` is a pool corresponding to an existent validator candidate.
- `function isActivePoolAdmin(address _poolAdminAddr) external view returns (bool)`
=> [Staking] Merge validator's 5 addresses to 3 addresses

contracts/interfaces/validator/ICandidateManager.sol, contracts/ronin/validator/CandidateManager.sol
https://skymavis.atlassian.net/browse/PSC-120?atlOrigin=eyJpIjoiODdlMDQyOTZmZDg3NDBiMzlhMGE1Yjc2MTBjMTY0MjgiLCJwIjoiaiJ9
`function getCommissionChangeSchedule(address _candidate) external view returns (CommissionSchedule memory);`
=> [CandidateManager] Add getter for schedule of commision change

contracts/interfaces/staking/IBaseStaking.sol, contracts/ronin/staking/BaseStaking.sol
Add new getter to fetch pool address from pool admin address
`function getPoolAddressOf(address _poolAdminAddr) external view override returns (address)`
=> [Staking] Support fetch pool address from pool admin address

contracts/extensions/RONTransferHelper.sol, contracts/ronin/staking/CandidateStaking.sol, contracts/ronin/staking/Staking.sol, contracts/ronin/validator/CoinbaseExecution.sol
- On RON transfer to unknown addresses, the gas forwarded is limited to `3500`. This follows these recommendations: [Link 1](https://github.com/ethereum/EIPs/issues/1285), [Link 2](https://ethereum.stackexchange.com/questions/59197/transfer-function-gas-limit-why-2-300), [Link 3](https://consensys.net/diligence/blog/2019/09/stop-using-soliditys-transfer-now/)
=> Limit gas to 3500

contracts/extensions/isolated-governance/bridge-operator-governance/BOsGovernanceProposal.sol, contracts/extensions/isolated-governance/bridge-operator-governance/BOsGovernanceRelay.sol, contracts/extensions/sequential-governance/GovernanceProposal.sol, contracts/extensions/sequential-governance/GovernanceRelay.sol, contracts/interfaces/IRoninGovernanceAdmin.sol, contracts/libraries/BridgeOperatorsBallot.sol, contracts/mainchain/MainchainGovernanceAdmin.sol, contracts/ronin/RoninGovernanceAdmin.sol, test/governance-admin/GovernanceAdmin.test.ts, test/helpers/utils.ts
-  Expose function for period and epoch that the bridge operator set is synced
- `contracts/mainchain/MainchainGovernanceAdmin.sol`: `relayBridgeOperators`
- `contracts/ronin/RoninGovernanceAdmin.sol`: `voteBridgeOperatorsBySignatures`
- `lastSyncedBridgeOperatorSetInfo`
=> [RoninGovernanceAdmin] Expose function & store bridge operator set

contracts/interfaces/validator/ICoinbaseExecution.sol, contracts/ronin/validator/CoinbaseExecution.sol, test/helpers/ronin-validator-set.ts, test/validator/RoninValidatorSet.test.ts
Emits list of validators and their corresponding amount of reward in `StakingRewardDistributed`.
| Old | New |
| --- | --- |
|  event StakingRewardDistributed(uint256 amount) | event StakingRewardDistributed(uint256 totalAmount, address[] consensusAddrs, uint256[] amounts) |
| event StakingRewardDistributionFailed(uint256 amount) | event StakingRewardDistributionFailed(uint256 totalAmount, address[] consensusAddrs, uint256[] amounts, uint256 contractBalance)|
=> [ValidatorSet] Add details for `StakingRewardDistributed` event

contracts/interfaces/staking/IBaseStaking.sol, contracts/interfaces/staking/ICandidateStaking.sol, contracts/interfaces/staking/IDelegatorStaking.sol, contracts/interfaces/staking/IRewardPool.sol, contracts/interfaces/staking/IStaking.sol, contracts/mocks/MockStaking.sol, contracts/ronin/staking/BaseStaking.sol, contracts/ronin/staking/CandidateStaking.sol, contracts/ronin/staking/DelegatorStaking.sol, contracts/ronin/staking/RewardCalculation.sol, contracts/ronin/staking/Staking.sol, contracts/ronin/validator/CoinbaseExecution.sol, contracts/ronin/validator/EmergencyExit.sol, contracts/ronin/validator/SlashingExecution.sol, test/integration/ActionSlashValidators.test.ts, test/staking/RewardCalculation.test.ts, test/staking/Staking.test.ts, test/validator/EmergencyExit.test.ts, test/validator/RoninValidatorSet.test.ts
- Rename internal methods and modifier for clarity. 
- Active pool: pool of a working candidate,
- Existing pool: pool of any candidate, including exited ones. 
- Rename `getStakingPool` to `getPoolDetail`, and remove pre-check.
- Add `exec-` prefix for cross-contract methods.
- Change error messages to custom errors.
| Old | New |
| ---- | ---- |
|  `function getStakingPool(address _poolAddr)` | `function getPoolDetail(address _poolAddr)` |
| `function isActivePoolAdmin(address _poolAdminAddr) public view returns (bool)` | `function isAdminOfActivePool(address _poolAdminAddr) public view returns (bool)` |
=> [Staking] Rename for clarity between pools and active pools

contracts/interfaces/validator/info-fragments/ICommonInfo.sol, contracts/interfaces/validator/info-fragments/IValidatorInfo.sol, contracts/ronin/validator/RoninValidatorSet.sol, contracts/ronin/validator/storage-fragments/ValidatorInfoStorage.sol
Add `Err-` prefix to custom errors for consistency.
=> [ValidatorSet] Add prefix for custom errors

contracts/ronin/validator/CoinbaseExecution.sol, contracts/ronin/validator/storage-fragments/TimingStorage.sol
- Fix bug of period start block should not be updated at the beginning of each epoch.
- Fix visibility of `_isPeriodEnding` to internal.
=> [ValidatorSet] Incorrect current period start at block

contracts/interfaces/staking/IRewardPool.sol, contracts/ronin/staking/RewardCalculation.sol, test/staking/RewardCalculation.test.ts
- Update the lowest amount in a period when claiming rewards
=> [RewardCalculation] Update lowest amount in period when claiming rewards

contracts/ronin/slash-indicator/CreditScore.sol, contracts/ronin/staking/RewardCalculation.sol
Since the gas consumption is already handled in EVM, the current check is redundant and could be safely removed.
[SSTORE Documentation](https://github.com/wolflo/evm-opcodes/blob/main/gas.md#a7-sstore): 
```
If new_val == current_val (no-op):
gas_cost += 100
```
=> Remove redundant check before storage assignment

contracts/interfaces/slash-indicator/ICreditScore.sol, contracts/ronin/slash-indicator/CreditScore.sol, contracts/ronin/validator/CandidateManager.sol, contracts/ronin/validator/CoinbaseExecution.sol, test/slash/CreditScore.test.ts
https://skymavis.atlassian.net/jira/software/projects/PSC/boards/47?selectedIssue=PSC-168
- Reset the credit score when the candidate is revoked
- Emit the event `CreditScoresUpdated` with scores of `0`s.
- Add `exec-` prefix to method name for consistency.
- ValidatorSet
- SlashIndicator
=> [CreditScore] Reset credit score after revoking

contracts/interfaces/staking/ICandidateStaking.sol, contracts/interfaces/staking/IStaking.sol, contracts/mocks/MockStaking.sol, contracts/mocks/validator/MockValidatorSet.sol, contracts/ronin/staking/CandidateStaking.sol, contracts/ronin/staking/DelegatorStaking.sol, contracts/ronin/staking/RewardCalculation.sol, contracts/ronin/staking/Staking.sol, contracts/ronin/validator/CandidateManager.sol, contracts/ronin/validator/CoinbaseExecution.sol, pull_request_template.md, test/integration/ActionSlashValidators.test.ts, test/slash/CreditScore.test.ts, test/staking/Staking.test.ts, test/validator/RoninValidatorSet-Candidate.test.ts, test/validator/RoninValidatorSet-CoinbaseExecution.test.ts
https://skymavis.atlassian.net/browse/PSC-174?atlOrigin=eyJpIjoiM2UzNWE4Mjk0ZDAyNGNiZTlhMDQ5MTk4M2JmNjc2OTciLCJwIjoiaiJ9
- Transfer unclaimed reward for the candidates on revoking
The table below shows following info:
- **Init data**: new storage field is declared and need initialized.
- **Dependent**: need to be changed due to changes in other contracts.
| **Contract name** | **ABI** | **Init data** | **Dependent** |
|-------------------|:-------:|:-------------:|:-------------:|
| BridgeTracking    |         |               |               |
| GovernanceAdmin   |         |               |               |
| Maintenance       |         |               |               |
| SlashIndicator    |         |               |               |
| Staking           | …
=> [Staking] Send last reward for revoked candidates

contracts/interfaces/IMaintenance.sol, contracts/ronin/Maintenance.sol, test/maintainance/Maintenance.test.ts
https://skymavis.atlassian.net/browse/PSC-174?atlOrigin=eyJpIjoiM2UzNWE4Mjk0ZDAyNGNiZTlhMDQ5MTk4M2JmNjc2OTciLCJwIjoiaiJ9
| **Contract name** | **ABI** | **Init data** | **Dependent** |
|-------------------|:-------:|:-------------:|:-------------:|
| BridgeTracking    |         |               |               |
| GovernanceAdmin   |         |               |               |
| Maintenance       |   [x]   |               |               |
| SlashIndicator    |         |               |               |
| Staking           |         |               |               |
| …
=> [Maintenance] Cancel maintenance schedule

contracts/extensions/sequential-governance/CoreGovernance.sol, contracts/extensions/sequential-governance/GovernanceProposal.sol, contracts/extensions/sequential-governance/GovernanceRelay.sol, contracts/ronin/RoninGovernanceAdmin.sol, hardhat.config.ts, test/governance-admin/GovernanceAdmin.test.ts
https://skymavis.atlassian.net/browse/PSC-177?atlOrigin=eyJpIjoiZTBiNzJlNDhhYzI1NGQwOWE3MzQ4ZGVlMmYzZjBjYmIiLCJwIjoiaiJ9
New proposal can be created by these following methods:
1. `proposeProposalStructAndCastVotes`
2. `proposeProposalForCurrentNetwork`
3. `proposeGlobal`
4. `proposeGlobalProposalStructAndCastVotes`
All methods except the first one calculate incorrect `round` number when the proposal with previous round number is expired. This PR fixes this by checking whether the previous proposal is expired and updating the `round` number accordingly.
=> [GA] Fix wrong calculation of `round`

contracts/interfaces/IMaintenance.sol, contracts/ronin/Maintenance.sol, hardhat.config.ts, src/config.ts, src/deploy/proxy/maintenance-proxy.ts, src/utils.ts, test/helpers/fixture.ts, test/maintainance/Maintenance.test.ts
https://skymavis.atlassian.net/browse/PSC-179?atlOrigin=eyJpIjoiYWZhMmVhMDA0YjExNDVkNjhlODA0YzNkZDcxYWMxZjEiLCJwIjoiaiJ9
- Prevent the second schedule within 3 days from the previous schedule
- Increase test timeout
| **Contract name** | **ABI** | **Init data** | **Dependent** |
|-------------------|:-------:|:-------------:|:-------------:|
| BridgeTracking    |         |               |               |
| GovernanceAdmin   |         |               |               |
| Maintenance       |  [x]    |    [x]           |               |
| SlashIndicator    |         | …
=> [Maintenance] Prevent second schedule within 3 days from the previous schedule

contracts/interfaces/staking/ICandidateStaking.sol, contracts/ronin/staking/CandidateStaking.sol, contracts/ronin/staking/Staking.sol, contracts/ronin/validator/CoinbaseExecution.sol, src/config.ts, src/deploy/proxy/staking-proxy.ts, src/utils.ts, test/helpers/fixture.ts, test/staking/Staking.test.ts, test/validator/RoninValidatorSet-Candidate.test.ts
Validator commission rate must not exceed 20%
| ----------------- | :-------: | :-----: | :-----------: | :-----------: |
| BridgeTracking    |       |         |               |               |
| Staking           |    [x]    |   [x]   |      [x]      |               |
| …
=> [Staking] Validator commission rate must not exceed 20%

contracts/ronin/BridgeTracking.sol, contracts/ronin/validator/storage-fragments/TimingStorage.sol
Remove redundant check of period number.
| **Contract name** |**Logic**| **ABI** | **Init data** | **Dependent** |
|-------------------|:---:|:-------:|:-------------:|:-------------:|
| BridgeTracking    |    [x]|     |               |               |
| GovernanceAdmin   |     |    |               |               |
| Maintenance       |      |    |           |               |
| SlashIndicator    |         |  |             |               |
| Staking           |        |        |     |               |
| StakingVesting    |         |   |            |               |
| …
=> [BridgeTracking] Redundant check of period number

contracts/ronin/validator/CoinbaseExecution.sol
Wrong args when calling `checkManyMaintained`
| Staking           |           |         | …
=> [ValidatorSet] Validators May Have The Wrong Block Producer Status

contracts/ronin/validator/CoinbaseExecution.sol, test/slash/CreditScore.test.ts
First updating credit scores and then updating the `_currentPeriodStartAtBlock` variable in the `CoinbaseExecution` contract.
| SlashIndicator    |           | …
=> [ValidatorSet] Possible To Acquire Credit Score While In Maintenance

contracts/multi-chains/RoninTrustedOrganization.sol
- Adds a check when updating a trusted organization to ensure that the consensus, governor, and bridge voter addresses are all distinct from each other in `updateTrustedOrganizations` method.
| Maintenance       |           |         | …
=> [TrustedOrg] Lack of Check When Updating Trusted Organization

contracts/ronin/staking/DelegatorStaking.sol
- Add check of `ErrAdminOfAnyActivePoolForbidden` for `delegateRewards`
| Staking …
=> [Staking] Possible For A Pool Admin to Delegate To A Different Pool

contracts/ronin/RoninGatewayV2.sol
Apply [Checks-Effects-Interactions Pattern](https://docs.soliditylang.org/en/v0.6.12/security-considerations.html#use-the-checks-effects-interactions-pattern) on all calls to `bridgeTrackingContract.handleVoteApproved`
| Maintenance       | …
=> [RoninGateway] Fix Reentrancy Attack

contracts/ronin/slash-indicator/SlashBridgeVoting.sol, test/integration/Configuration.test.ts, test/slash/SlashIndicator.test.ts
| SlashIndicator    |     [x]      |         |               |               |
| Staking           |           |         |               |               |
| …
=> [SlashIndicator] Fix setter in bridge voting configs

contracts/ronin/validator/CoinbaseExecution.sol, contracts/ronin/validator/storage-fragments/ValidatorInfoStorage.sol, test/validator/RoninValidatorSet-CoinbaseExecution.test.ts
https://skymavis.atlassian.net/browse/PSC-198?atlOrigin=eyJpIjoiNWIzZTc4MzBjOWQ0NDQ0ZGI5YWJjOTlmM2E0YzIxYTIiLCJwIjoiaiJ9
When updating the validator set from `[A, B, C]` to `[A, C, B]`, the flag mapping of `C` is incorrectly updated in `_setNewValidatorSet`. This flag mapping is later updated correctly in `_revampRoles` method. However, this is still a potential issue and needs to be mitigated. …
=> [ValidatorSet] Fix private method of setting new validator set

contracts/interfaces/validator/info-fragments/IJailingInfo.sol, contracts/mocks/validator/MockValidatorSet.sol, contracts/ronin/validator/storage-fragments/JailingStorage.sol
Add method check bridge slashing tier-1: `checkBridgeRewardDeprecated`
| Staking           | …
=> [ValidatorSet] Add method check bridge slashing tier-1

contracts/ronin/validator/CoinbaseExecution.sol
Currently: bridge miss vote: `> 10% or > 20%` -> slash
Change to: bridge miss vote: `>= 10% or >= 20%` -> slash
| SlashIndicator    |           |         | …
=> [ValidatorSet] Change slash point of bridge operating condition

contracts/interfaces/slash-indicator/ISlashDoubleSign.sol, contracts/mocks/MockPrecompile.sol, contracts/mocks/MockSlashIndicatorExtended.sol, contracts/mocks/precompile-usages/MockPCUValidateDoubleSign.sol, contracts/precompile-usages/PCUValidateDoubleSign.sol, contracts/ronin/slash-indicator/SlashDoubleSign.sol, contracts/ronin/slash-indicator/SlashIndicator.sol, contracts/ronin/slash-indicator/SlashUnavailability.sol, src/config.ts, src/deploy/proxy/slash-indicator-proxy.ts, src/utils.ts, test/helpers/encoder.ts, test/helpers/fixture.ts, test/helpers/governance-admin.ts, test/precompile-usages/PrecompileUsageValidateDoubleSign.test.ts, test/slash/SlashIndicator.test.ts
> **Warning**
> This PR may cause backward-incompatible due to change required in precompiled contract.
- Allow to double signing without coinbase check
- Mark double sign slash as cannot bailout
- Only admin can slash double sign
- Remove check of slashee must be validator
- Expose `doubleSigningOffsetLimitBlock` to indicate the at most block number can submit the evidence
- Set `doubleSigningOffsetLimitBlock` to `~14 days`
- **Add `_consensusAddr` param to precompiled call**, which may cause backward-incompatible
| **Contract name** | …
=> [SlashIndicator] Improve slash double sign

contracts/extensions/isolated-governance/bridge-operator-governance/BOsGovernanceProposal.sol
Remove early return early and have all votes be processed
| BridgeTracking    |           |         |               |        [x]       |
| GovernanceAdmin   |    [x]       |         |               |               |
| Maintenance       |           |         |               |        [x]       |
| SlashIndicator    |           |         |               |        [x]       |
| Staking           | …
=> [GA] For Loop Should Not Return Early When Casting Vote For Bridge Operators

contracts/ronin/staking/CandidateStaking.sol
- Check commission rate while applying for candidate
| Staking           |   [x]        | …
=> [Staking] Check commission rate while applying candidate

contracts/interfaces/validator/info-fragments/IJailingInfo.sol, contracts/mocks/validator/MockValidatorSet.sol, contracts/ronin/validator/storage-fragments/JailingStorage.sol
Remove methods to reduce contract size. DApp must migrate to these new methods.
- Add methods for checking deprecated reward of:
- `mining()`
- `miningAtPeriod(uint256)`
- `bridgeAtLatestPeriod()`
- `bridgeAtPeriod(uint256)`
- Remove methods:
- `function checkBridgeRewardDeprecated(address _consensusAddr) external view returns (bool _result)`
- `function checkMiningRewardDeprecated(address[] calldata _blockProducers) external view returns (bool[] memory);` 
- `function checkMiningRewardDeprecatedAtPeriod(address[] calldata _blockProducers, uint256 _period) external view returns (bool[] memory);`
- **Dependent**: …
=> [ValidatorSet] Add getter for bridge slash at period. Remove batch getters.

contracts/extensions/consumers/GlobalConfigConsumer.sol, contracts/mocks/MockStaking.sol, contracts/mocks/MockTransferFallback.sol, contracts/ronin/staking/CandidateStaking.sol, contracts/ronin/staking/Staking.sol, contracts/ronin/validator/CandidateManager.sol, contracts/ronin/validator/CoinbaseExecution.sol, contracts/ronin/validator/EmergencyExit.sol, contracts/ronin/validator/storage-fragments/TimingStorage.sol, test/transfer/PaymentFallback.test.ts
In low-level call `<contract>.call{ value: _amount, gas: _gas }()`, the actual amount of gas stipend forwarding to the external is `2300 + _gas`. The compiler determines this, regardless of hardfork of the chain.
Since we design that the recipient will receive 3500 gas (as in #127), this PR reduces the number of 3500 in the parameter of `.call` to 1200.
No slot of storage is shuffled after this PR.
|-------------------|:---------:|:-------:|:-------------:|:----------- …
=> Fix addition gas in external calls

contracts/ronin/validator/CandidateManager.sol
Previous code does not handle updating size of revoked candidates array, which causes false emission of event `CreditScoreUpdated(address(0))`.
| SlashIndicator    | …
=> [ValidatorSet] Handling 0-length of memory array

contracts/ronin/validator/CoinbaseExecution.sol
| Staking           |           |         |               |               |
| StakingVesting …
=> [ValidatorSet] Fix improper validation of bridge tracking response

contracts/ronin/gateway/PauseEnforcer.sol
| PauseEnforcer      |     [x]      |    [x]     |               |               |
=> [PauseEnforcer] Expose method to change target 

contracts/libraries/Math.sol, contracts/ronin/slash-indicator/SlashUnavailability.sol, contracts/ronin/validator/CoinbaseExecution.sol
- Assert the block number that validator is put in jail are updated correctly:
- No update if the jail duration is 0.
- The `current block` is excluded when calculating with jail duration.
- Check the jail status of validators at the `current block + 1`
| GovernanceAdmin   |           |         |               | …
=> [Slash|ValidatorSet] Fix calculation of jail until block

contracts/ronin/Maintenance.sol, test/maintainance/Maintenance.test.ts
Wrong assertion caused validators cannot set maintenance at `minBlockDuration` but `minBlockDuration + 1 epoch`.
| Maintenance       |     [x]     |         |               |               |
| SlashIndicator    |           |         | …
=> [Maintenance] Fix assertion of maintenance elapsed

contracts/ronin/staking/DelegatorStaking.sol, test/staking/Staking.test.ts
Remove cooldown when undelegate for renouncing candidate
| Staking           |     [x] …
=> [Staking] Remove cooldown when undelegate for renouncing candidate

test/bridge/BridgeTracking.test.ts, test/bridge/GatewayPauseEnforcer.test.ts, test/bridge/RoninGatewayV2.test.ts, test/governance-admin/GovernanceAdmin.test.ts, test/helpers/candidate-manager.ts, test/helpers/governance-admin.ts, test/helpers/ronin-validator-set.ts, test/helpers/staking-vesting.ts, test/helpers/staking.ts, test/helpers/utils.ts, test/integration/ActionBridgeTracking.test.ts, test/integration/ActionSlashValidators.test.ts, test/integration/ActionWrapUpEpoch.test.ts, test/integration/Configuration.test.ts, test/maintainance/Maintenance.test.ts, test/precompile-usages/PrecompileUsageSortValidators.test.ts, test/precompile-usages/PrecompileUsageValidateDoubleSign.test.ts, test/slash/CreditScore.test.ts, test/slash/SlashIndicator.test.ts, test/sorting/QuickSort.test.ts, test/staking/Staking.test.ts, test/validator/ArrangeValidators.test.ts, test/validator/EmergencyExit.test.ts, test/validator/RoninValidatorSet-Candidate.test.ts, test/validator/RoninValidatorSet-CoinbaseExecution.test.ts
The `hardhat-deploy` package uses higher version of `ethers` which causes the following test case failed.
```
console.log(await validatorContract.getJailUntils(expectingValidatorSet));
console.log(BigNumber.from(blockNumber).add(jailDurationForUnavailabilityTier2Threshold));
```
Before upgrade
```
[ BigNumber { value: "57658" } ]
BigNumber { value: "57658" }
```
After upgrade
```
[ BigNumber { _hex: '0xe13a', _isBigNumber: true } ]
BigNumber { value: "57658" }
```
=> [test] Fix assertion on arrays of BigNumbers
