test/helpers/fixture.ts, test/integration/ActionSubmitReward.test.ts, test/integration/Configuration.test.ts
=> [Test] Update small values for `*blockRewardAmount` in tests

contracts/interfaces/validator/ICandidateManager.sol, contracts/ronin/validator/CandidateManager.sol, contracts/ronin/validator/CoinbaseExecution.sol, test/integration/ActionSlashValidators.test.ts, test/staking/Staking.test.ts
https://skymavis.atlassian.net/browse/PSC-102?atlOrigin=eyJpIjoiOTlkMmRiOTdjOWQxNDEyYmE4MzE4OGI2ZGY2ZGUxY2EiLCJwIjoiaiJ9
- Add a deadline to maintain minimum staking amount for validator candidates (#74)
=> Add deadline to maintain minimum staking amount for validator candidates

contracts/ronin/validator/CandidateManager.sol, test/staking/Staking.test.ts, test/validator/RoninValidatorSet.test.ts
- https://skymavis.atlassian.net/browse/PSC-112?atlOrigin=eyJpIjoiMjRhN2Q3NmVlYmI4NDYzYzg3NzhmNmM3ZTY1N2JhZGEiLCJwIjoiaiJ9
- Fix #57
=> [ValidatorSet] Prevent duplicated addresses among validators

contracts/ronin/staking/RewardCalculation.sol, contracts/ronin/validator/CoinbaseExecution.sol, test/staking/RewardCalculation.test.ts
=> [RoninValidatorSet] Help fix reward calculation

contracts/ronin/validator/CoinbaseExecution.sol
=> Fix bridge reward

contracts/interfaces/validator/info-fragments/ITimingInfo.sol, contracts/mocks/validator/MockRoninValidatorSetExtended.sol, contracts/mocks/validator/MockRoninValidatorSetOverridePrecompile.sol, contracts/mocks/validator/MockValidatorSet.sol, contracts/ronin/BridgeTracking.sol, contracts/ronin/RoninGatewayV2.sol, contracts/ronin/validator/CoinbaseExecution.sol, contracts/ronin/validator/storage-fragments/TimingStorage.sol, test/bridge/BridgeTracking.test.ts
- [BridgeTracking] Delay 1 epoch for upcoming votes
=> [BridgeTracking] Delay 1 epoch for upcoming votes

.github/workflows/unittest.yml
Using public runner instead of private runner for triggering tests.
=> Using public runner instead of private runner

contracts/extensions/sequential-governance/CoreGovernance.sol, test/governance-admin/GovernanceAdmin.test.ts
- Fix case of cannot create a new proposal after the expiry time of an executed proposal has passed.
=> [GovernanceAdmin] Fix checking expiry proposal

contracts/extensions/sequential-governance/CoreGovernance.sol, contracts/ronin/RoninGovernanceAdmin.sol, src/script/governance-admin-interface.ts, test/governance-admin/GovernanceAdmin.test.ts
- Support voting without signatures on the Ronin network (#121)
- Task: https://skymavis.atlassian.net/browse/PSC-126?atlOrigin=eyJpIjoiZWFjNzk3NTdiZGU2NDM1YmJiODc5Y2U4MGEzMmI0YjIiLCJwIjoiaiJ9
- `proposeProposalForCurrentNetwork`
- `castProposalVoteForCurrentNetwork`
=> Support voting without signatures on the Ronin network

contracts/extensions/GovernanceAdmin.sol, contracts/mainchain/MainchainGovernanceAdmin.sol, contracts/ronin/RoninGovernanceAdmin.sol, src/config.ts, src/deploy/mainchain-governance-admin.ts, src/deploy/ronin-governance-admin.ts, src/script/governance-admin-interface.ts, src/utils.ts, test/bridge/BridgeTracking.test.ts, test/governance-admin/GovernanceAdmin.test.ts, test/helpers/fixture.ts, test/integration/ActionSlashValidators.test.ts, test/integration/ActionSubmitReward.test.ts, test/integration/ActionWrapUpEpoch.test.ts, test/maintainance/Maintenance.test.ts, test/slash/CreditScore.test.ts, test/slash/SlashIndicator.test.ts, test/validator/ArrangeValidators.test.ts, test/validator/EmergencyExit.test.ts, test/validator/RoninValidatorSet.test.ts
=> [GovernanceAdmin] Separate domain separator

.github/workflows/unittest.yml, hardhat.config.ts, package.json, yarn.lock
The [@axieinfinity/hardhat-4byte-uploader](https://github.com/axieinfinity/hardhat-4byte-uploader) uploads 4-byte signature of *external method*s, *custom error*s to [Ethereum Signature Database](https://www.4byte.directory/).
This helps other teams debugging transaction error with ease.
Only selectors filterred from the contracts' compliation artifacts are uploaded to the DB. No sensitive data is read, or uploaded.
```
Generating typings for: 158 artifacts in dir: src/types for target: ethers-v5
Successfully generated 281 typings!
Compiled 158 Solidity files successfully
Processed 634 unique items from 160 ABIs
Added 340 selectors to database
Found 294 duplicates
Ignored 0 items
```
```
0x030081e7  ErrTrustedOrgCannotRenounce()
0xffcb4513  ErrUnauthorizedReceiveRON()	
0xaa8119d2 …
```
=> Add upload selectors plugin

contracts/extensions/isolated-governance/bridge-operator-governance/BOsGovernanceProposal.sol, contracts/ronin/RoninGovernanceAdmin.sol, test/governance-admin/GovernanceAdmin.test.ts
- Update the function to get bridge voter signatures.
- Method: `getBridgeOperatorVotingSignatures`
=> [RoninGovernanceAdmin] Update function to get bridge voter's signatures.

contracts/multi-chains/RoninTrustedOrganization.sol
=> [TrustedOrg] Incorrect update of bridge voter list

contracts/extensions/GatewayV2.sol, contracts/multi-chains/RoninTrustedOrganization.sol, contracts/ronin/slash-indicator/CreditScore.sol, contracts/ronin/slash-indicator/SlashBridgeOperator.sol, contracts/ronin/slash-indicator/SlashBridgeVoting.sol, contracts/ronin/slash-indicator/SlashDoubleSign.sol, contracts/ronin/slash-indicator/SlashUnavailability.sol, contracts/ronin/validator/storage-fragments/TimingStorage.sol, deployments/ronin-testnet/RoninGatewayV2Logic.json, deployments/ronin-testnet/RoninTrustedOrganizationLogic.json, deployments/ronin-testnet/RoninValidatorSetLogic.json, deployments/ronin-testnet/SlashIndicatorLogic.json
- Add names for returned variables in implementation contracts.
- No logic is updated.
- ABIs are provided with more info.
=> [*] Add names for returned variables

contracts/interfaces/slash-indicator/ISlashBridgeOperator.sol, contracts/ronin/slash-indicator/SlashBridgeOperator.sol, contracts/ronin/validator/CoinbaseExecution.sol, hardhat.config.ts, package.json, yarn.lock
https://skymavis.atlassian.net/browse/PSC-190?atlOrigin=eyJpIjoiMWEyNDQyZWQyOTk0NDk4ZThlZmQyNTdhYjBmMmE5ZGUiLCJwIjoiaiJ9
| SlashIndicator    |     [x]      |    [x] …
=> [Slash] Emit event for slashing bridge operator

test/integration/ActionSlashValidators.test.ts, test/integration/ActionSubmitReward.test.ts, test/maintainance/Maintenance.test.ts, test/validator/RoninValidatorSet-CoinbaseExecution.test.ts
https://skymavis.atlassian.net/browse/PSC-196?atlOrigin=eyJpIjoiMmMwNmExNzJmY2VjNGFlMzg0YWMwOGFkZDg2YjZlNjUiLCJwIjoiaiJ9
=> [Test] Add await for `expect ... emit` tests

package.json, yarn.lock
The storage layout has not been changed after the upgrade.
Reports of storage layout can be found in the attachments:
- [layout-4.6.0.txt](https://github.com/axieinfinity/ronin-dpos-contracts/files/10811490/layout-4.6.0.txt)
- [layout-4.7.3.txt](https://github.com/axieinfinity/ronin-dpos-contracts/files/10811491/layout-4.7.3.txt)
- [layout-4.8.1.txt](https://github.com/axieinfinity/ronin-dpos-contracts/files/10811588/layout-4.8.1.txt)
| Maintenance       |           |         | …
=> [Gateway] Update Openzeppelin Library to v4.7.3

deployments/ethereum/MainchainGatewayV2Logic.json, src/deploy/logic/mainchain-gateway-v2.ts
Mainly deploy MainchainGatewayV2Logic that missed at #200 
```sh
$ yarn hardhat deploy --network ethereum --tags MainchainGatewayV2Logic
deploying "MainchainGatewayV2Logic" (tx: 0xa5db6e43cbfa2db0c465d53a76090a5b9fc11355725755298a428a70c9ca92e3)...: deployed at 0xa67BA5315AF4961Eb937158032AF9300C657dAcD with 4504647 gas
```
=> [Deploy] Add deployment artifact for MainchainGatewayV2Logic

contracts/ronin/slash-indicator/SlashBridgeVoting.sol
The method `slashBridgeVoting` is now only revoked by admin.
| SlashIndicator    |     [x]     |         |               |               |
=> [SlashIndicator] Restrict slash bridge voting

hardhat.config.ts, src/upgrades/230406-update-slash-conditions.ts, src/upgrades/upgradeUtils.ts
- Validator slash:
- Tier 1: 100 blocks
- Tier 2: 500 blocks, slash amount: 1,000 RON
- Tier 3: 100 more blocks, slash amount: 1,000 RON
- Bridge Slash:
- Remove jail time
- Remove Tier 2 self-slash, i.e., nodes only lose the bridge reward and validator rewards
- Voting Slash:
- Slash amount: 1.000 RON
- `ValidatorSet`
- `SlashIndicator`
=> [config][SlashIndicator] Update slash configs

hardhat.config.ts, package.json, src/deploy/vault-forwarder.ts, src/script/governance-admin-interface.ts, src/script/proposal.ts, src/script/verify-address.ts, src/upgrades/230411-add-GVs.ts, src/utils.ts, test/helpers/fixture.ts, test/helpers/staking-vesting.ts, test/helpers/utils.ts, test/integration/ActionSlashValidators.test.ts, test/integration/ActionWrapUpEpoch.test.ts, test/precompile-usages/PrecompileUsageValidateDoubleSign.test.ts, test/validator/ArrangeValidators.test.ts, test/validator/EmergencyExit.test.ts, test/validator/RoninValidatorSet-Candidate.test.ts, test/validator/RoninValidatorSet-CoinbaseExecution.test.ts, yarn.lock
=> [config][TrustedOrg] Add 11 governing validators

src/upgrades/230411-add-GVs.ts
Using `proposeGlobal` instead of `proposeForCurrentNetwork`.
=> [config][TrustedOrg] Fix script of adding 11 governing validators 

.gitignore, contracts/interfaces/staking/ICandidateStaking.sol, contracts/ronin/gateway/PauseEnforcer.sol, contracts/ronin/staking/CandidateStaking.sol, contracts/ronin/staking/Staking.sol, contracts/ronin/validator/CoinbaseExecution.sol, test/staking/Staking.test.ts, test/validator/RoninValidatorSet-Candidate.test.ts
- This PR is mainly to add the minimum rate of the validator commission.
| Staking …
=> [Validator|Staking] Add min commission rate

src/upgrades/230406-update-slash-conditions.ts, src/upgrades/230411-add-GVs.ts, src/upgrades/230515-change-min-commission-rate-5-percent.ts, src/upgrades/230516-set-pause-enforcer-mainchain-gateway.ts, src/upgrades/upgradeUtils.ts
Script executed
https://app.roninchain.com/tx/0x9a25a1cd3a16ba62e5c850adf797b304aef5b75952f73efcf39d2f4afb312dd2
=> [Upgrade] Fix set commission rate script
